# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'IUUTour' do
platform :ios, '7.0'
pod 'ReactiveCocoa', '2.5'

#pod 'MJRefresh'
#pod 'AMapNavi'
#pod 'AMapLocation' #定位SDK
##pod 'AMap3DMap' #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
#pod 'AMapSearch' #搜索服务SDK

end

